# Generated by Django 4.1.5 on 2023-01-15 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="title",
            new_name="todo",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="body",
        ),
    ]
