# Generated by Django 4.1.5 on 2023-01-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0003_todo_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="user",
        ),
    ]
